from __future__ import annotations

from typing import Any, Protocol

from app.models.call_event import CallEvent
from app.models.lead import Lead
from app.schemas.call_events import CallEventCreate
from app.schemas.leads import LeadCreate


class LeadsRepositoryContract(Protocol):
    async def get_lead(self, lead_id: int) -> Lead | None: ...
    async def get_lead_for_update(self, lead_id: int) -> Lead | None: ...
    async def count_leads(self, condition: Any) -> int: ...
    async def list_leads(self, *, condition: Any, limit: int, offset: int) -> list[Lead]: ...
    async def wallet_balance_cents(self, user_id: int) -> int: ...
    async def create_lead(self, body: LeadCreate, user_id: int) -> Lead: ...
    async def add_lead_activity(self, *, user_id: int, action: str, lead_id: int, meta: dict) -> None: ...
    async def add_wallet_debit_for_claim(self, *, user_id: int, lead_id: int, lead_name: str, price_cents: int) -> None: ...
    async def mark_lead_claimed(self, lead: Lead, user_id: int) -> None: ...
    async def persist_lead(self, lead: Lead) -> Lead: ...
    async def soft_delete_lead(self, lead: Lead) -> None: ...
    async def create_call_event(self, *, lead_id: int, user_id: int, body: CallEventCreate) -> CallEvent: ...
    async def add_call_activity(
        self,
        *,
        user_id: int,
        event_id: int,
        lead_id: int,
        outcome: str,
        duration_seconds: int | None,
    ) -> None: ...
    async def count_calls(self, lead_id: int) -> int: ...
    async def list_calls(self, *, lead_id: int, limit: int, offset: int) -> list[CallEvent]: ...
    async def commit(self) -> None: ...


class TopicNotifierContract(Protocol):
    async def __call__(self, *topics: str) -> None: ...
