export interface ArchNode {
  id: string
  label: string
  sublabel?: string
  layer: 'frontend' | 'api-gateway' | 'backend' | 'infra' | 'external'
  position: [number, number, number]
  size: [number, number, number]
  color: string
  description?: string
  connections?: string[]
  children?: ArchNode[]
  tags?: string[]
  meta?: Record<string, string>
}

export const LAYER_CONFIG = {
  frontend: { color: '#3b82f6', label: 'Frontend Layer', y: 7, icon: '🖥' },
  'api-gateway': { color: '#8b5cf6', label: 'API Gateway', y: 2, icon: '🔌' },
  backend: { color: '#10b981', label: 'Backend Layer', y: -3, icon: '⚙️' },
  infra: { color: '#f59e0b', label: 'Infrastructure', y: -7, icon: '🗄' },
  external: { color: '#ec4899', label: 'External Services', y: -11, icon: '☁️' },
} as const

export const LAYER_ORDER = ['frontend', 'api-gateway', 'backend', 'infra', 'external'] as const

export const ARCHITECTURE_NODES: ArchNode[] = [
  // ===================== FRONTEND LAYER =====================
  {
    id: 'react-spa',
    label: 'Myle SPA',
    sublabel: 'Vite + React 19 + TypeScript 6',
    layer: 'frontend',
    position: [-4, 5.5, 0],
    size: [4.5, 1.4, 3.5],
    color: '#3b82f6',
    description: 'Main user-facing single-page application with 63 pages, 62 custom hooks, 10 Zustand stores, and 54 utility modules. Built with Vite 8 for instant HMR.',
    tags: ['react', 'vite', 'spa', 'pwa'],
    connections: ['fastapi-v1', 'fastify-crm'],
    meta: { Pages: '63', Hooks: '62', Stores: '10', Modules: '54', Port: '5174' },
  },
  {
    id: 'crm-admin',
    label: 'CRM Admin',
    sublabel: 'Next.js 14 + React 18',
    layer: 'frontend',
    position: [4, 5.5, 0],
    size: [3.5, 1.2, 3],
    color: '#60a5fa',
    description: 'Admin dashboard built with Next.js 14 App Router. Handles admin operations, QA labs, and back-office management.',
    tags: ['nextjs', 'admin', 'ssr'],
    connections: ['fastify-crm'],
    meta: { Port: '4001', Router: 'App Router' },
  },
  {
    id: 'ui-components',
    label: 'UI Components',
    sublabel: 'shadcn/ui · 21 primitives',
    layer: 'frontend',
    position: [-5, 4, 2.5],
    size: [3, 0.8, 2],
    color: '#93c5fd',
    description: '21 shadcn/ui primitives plus custom components for dashboard, analytics, training, wallet, and video.',
    tags: ['shadcn', 'tailwind', 'ui'],
  },
  {
    id: 'state-mgmt',
    label: 'State Management',
    sublabel: 'Zustand 5 + React Query 5',
    layer: 'frontend',
    position: [0, 4, 2.5],
    size: [3.5, 0.8, 2],
    color: '#93c5fd',
    description: '10 Zustand stores for client-side UI state + TanStack React Query 5 for server state caching and synchronization.',
    tags: ['zustand', 'tanstack', 'state'],
    connections: ['fastapi-v1'],
  },
  {
    id: 'realtime-client',
    label: 'Socket.IO Client',
    sublabel: 'Real-time updates',
    layer: 'frontend',
    position: [5, 4, 2.5],
    size: [2.5, 0.8, 1.8],
    color: '#93c5fd',
    description: 'Socket.IO v4 client for real-time lead updates, live funnel, and presence.',
    tags: ['socketio', 'realtime'],
    connections: ['realtime-socketio'],
  },
  {
    id: 'pwa-capacitor',
    label: 'PWA + Capacitor',
    sublabel: 'Android wrapper',
    layer: 'frontend',
    position: [-4, 4, -2.5],
    size: [2.5, 0.7, 1.8],
    color: '#bfdbfe',
    description: 'Progressive Web App with service worker + Capacitor 8 Android wrapper for mobile deployment.',
    tags: ['pwa', 'capacitor', 'android'],
  },
  {
    id: 'analytics-ui',
    label: 'Analytics Views',
    sublabel: 'Charts · Funnel · Trends',
    layer: 'frontend',
    position: [4, 4, -2.5],
    size: [3, 0.7, 2],
    color: '#bfdbfe',
    description: 'Live funnel visualization, pipeline charts, daily trends, and leaderboard components.',
    tags: ['analytics', 'charts'],
    connections: ['api-analytics'],
  },

  // ===================== API GATEWAY LAYER =====================
  {
    id: 'fastapi-v1',
    label: 'FastAPI v1',
    sublabel: 'Python 3.12 · Port 8000',
    layer: 'api-gateway',
    position: [-4, 0.5, -1],
    size: [4.5, 1.6, 3.5],
    color: '#8b5cf6',
    description: 'Main REST API — 45 route modules, JWT auth, SQLAlchemy async, APScheduler jobs. ASGI server via Uvicorn/Gunicorn.',
    tags: ['fastapi', 'python', 'asgi', 'rest'],
    connections: ['services-layer', 'models-db', 'bg-jobs', 'db-postgres', 'redis-cache', 'sentry'],
    meta: { Routes: '45 modules', Port: '8000', Auth: 'JWT cookies', ORM: 'SQLAlchemy 2.0' },
  },
  {
    id: 'fastify-crm',
    label: 'Fastify CRM',
    sublabel: 'Node.js · Prisma · Port 4000',
    layer: 'api-gateway',
    position: [4, 0.5, -1],
    size: [4, 1.4, 3],
    color: '#a78bfa',
    description: 'CRM microservice using Fastify 5 + Prisma 6 ORM + Socket.IO. Handles lead FSM, pool management, wallet, escalation.',
    tags: ['fastify', 'node', 'prisma', 'microservice'],
    connections: ['models-db', 'realtime-socketio', 'redis-cache', 'db-postgres'],
    meta: { Routes: '8 modules', Port: '4000', ORM: 'Prisma 6', Realtime: 'Socket.IO' },
  },

  // FastAPI route groups (children conceptually)
  {
    id: 'api-auth',
    label: 'Auth',
    sublabel: 'JWT · Login · Register',
    layer: 'api-gateway',
    position: [-6, 0.5, 2.5],
    size: [2.2, 0.7, 1.8],
    color: '#c4b5fd',
    description: 'Authentication endpoints: login, register, refresh tokens, JWT cookie management.',
    connections: ['fastapi-v1'],
    tags: ['auth', 'jwt', 'security'],
  },
  {
    id: 'api-leads',
    label: 'Leads',
    sublabel: 'CRUD · CTCS · Lifecycle',
    layer: 'api-gateway',
    position: [-3.5, 0.5, 2.5],
    size: [2.2, 0.7, 1.8],
    color: '#c4b5fd',
    description: 'Lead management: CRUD, CTCS processing, lifecycle state machine, execution enforcement.',
    connections: ['fastapi-v1'],
    tags: ['leads', 'crm', 'ctcs'],
  },
  {
    id: 'api-wallet',
    label: 'Wallet & Finance',
    sublabel: 'Payments · Budgets',
    layer: 'api-gateway',
    position: [-1, 0.5, 2.5],
    size: [2.2, 0.7, 1.8],
    color: '#c4b5fd',
    description: 'Wallet operations, recharges, budgets, finance surfaces, invoices, billing.',
    connections: ['fastapi-v1'],
    tags: ['wallet', 'payments', 'finance'],
  },
  {
    id: 'api-analytics',
    label: 'Analytics',
    sublabel: 'Reports · Trends',
    layer: 'api-gateway',
    position: [1.5, 0.5, 2.5],
    size: [2.2, 0.7, 1.8],
    color: '#c4b5fd',
    description: 'Analytics and reporting: trends, metrics, exports, team reports, daily reports.',
    connections: ['fastapi-v1'],
    tags: ['analytics', 'reports'],
  },
  {
    id: 'api-team',
    label: 'Team & Org',
    sublabel: 'Tracking · Members',
    layer: 'api-gateway',
    position: [4, 0.5, 2.5],
    size: [2.2, 0.7, 1.8],
    color: '#c4b5fd',
    description: 'Team management: tracking, attendance, members, org tree, approvals.',
    connections: ['fastapi-v1'],
    tags: ['team', 'org', 'tracking'],
  },
  {
    id: 'api-system',
    label: 'System & Admin',
    sublabel: 'Settings · Downloads',
    layer: 'api-gateway',
    position: [6.5, 0.5, 2.5],
    size: [2.2, 0.7, 1.8],
    color: '#c4b5fd',
    description: 'System endpoints: settings, admin operations, downloads, certificates.',
    connections: ['fastapi-v1'],
    tags: ['system', 'admin', 'settings'],
  },

  // ===================== BACKEND LAYER =====================
  {
    id: 'services-layer',
    label: '71 Service Modules',
    sublabel: 'Business logic layer',
    layer: 'backend',
    position: [-3.5, -4.5, 1.5],
    size: [3.5, 1.2, 3],
    color: '#10b981',
    description: '71 service modules spanning all business domains: lead management, team operations, wallet, analytics, notifications, compliance, and more.',
    tags: ['services', 'business-logic', 'python'],
    connections: ['models-db', 'middleware-stack'],
    meta: { Total: '71 modules', Pattern: 'Service layer' },
  },
  {
    id: 'models-db',
    label: '42 ORM Models',
    sublabel: 'SQLAlchemy async',
    layer: 'backend',
    position: [0.5, -4.5, 1.5],
    size: [3, 1.2, 2.8],
    color: '#34d399',
    description: '42 SQLAlchemy 2.0 ORM models with asyncpg driver. Alembic migrations for schema management.',
    tags: ['sqlalchemy', 'orm', 'models', 'alembic'],
    connections: ['db-postgres'],
    meta: { Models: '42', Migrations: 'Alembic' },
  },
  {
    id: 'middleware-stack',
    label: 'Middleware Stack',
    sublabel: 'Security · Rate Limit · Logging',
    layer: 'backend',
    position: [4.5, -4.5, 1.5],
    size: [3, 1, 2.5],
    color: '#34d399',
    description: '5 middleware layers: AccessLog, AuthRateLimit, RequestId, SecurityHeaders, CORS.',
    tags: ['middleware', 'security', 'logging'],
    connections: ['fastapi-v1'],
  },
  {
    id: 'bg-jobs',
    label: 'APScheduler Jobs',
    sublabel: '9 scheduled tasks',
    layer: 'backend',
    position: [-3.5, -4.5, -1.8],
    size: [3, 0.9, 2.2],
    color: '#6ee7b7',
    description: '9 scheduled background jobs: daily summaries, compliance checks, reminders, email digests, data cleanup.',
    tags: ['scheduler', 'cron', 'background'],
    meta: { Jobs: '9', Engine: 'APScheduler' },
  },
  {
    id: 'realtime-socketio',
    label: 'Socket.IO Server',
    sublabel: 'Gateway · Rooms · Presence',
    layer: 'backend',
    position: [0.5, -4.5, -1.8],
    size: [3, 0.9, 2.2],
    color: '#6ee7b7',
    description: 'Full Socket.IO infrastructure in CRM microservice: gateway, room management, presence tracking, adapter, rate-limiter, batcher.',
    tags: ['socketio', 'realtime', 'websocket'],
    connections: ['redis-cache'],
  },
  {
    id: 'integrations',
    label: 'Integrations',
    sublabel: 'R2 · WhatsApp · n8n · OCR',
    layer: 'backend',
    position: [4.5, -4.5, -1.8],
    size: [3, 0.9, 2.2],
    color: '#6ee7b7',
    description: 'External integrations: Cloudflare R2 storage, WhatsApp Cloud API, n8n webhooks, OCR (Tesseract), PDF generation (ReportLab).',
    tags: ['integrations', 'external', 'api'],
    connections: ['r2-storage', 'whatsapp', 'n8n'],
  },

  // ===================== INFRA LAYER =====================
  {
    id: 'db-postgres',
    label: 'PostgreSQL 16',
    sublabel: 'Primary database · asyncpg',
    layer: 'infra',
    position: [-3.5, -8.5, 0],
    size: [3.5, 1.4, 3],
    color: '#f59e0b',
    description: 'Primary PostgreSQL 16 database with asyncpg driver. Shared across FastAPI backend and Fastify CRM microservice.',
    tags: ['postgresql', 'database', 'asyncpg'],
    meta: { Version: '16', Driver: 'asyncpg', ORMs: 'SQLAlchemy + Prisma' },
  },
  {
    id: 'redis-cache',
    label: 'Redis 7',
    sublabel: 'Cache · Queue · Pub/Sub',
    layer: 'infra',
    position: [0.5, -8.5, 0],
    size: [3, 1.2, 2.5],
    color: '#fbbf24',
    description: 'Redis 7: general caching, BullMQ job queues, Socket.IO adapter, rate limiting, session store.',
    tags: ['redis', 'cache', 'queue', 'pubsub'],
    meta: { Version: '7', Uses: 'Cache · Queue · Pub/Sub' },
  },
  {
    id: 'r2-storage',
    label: 'Cloudflare R2',
    sublabel: 'S3-compatible storage',
    layer: 'infra',
    position: [4.5, -8.5, 0],
    size: [2.5, 1, 2.2],
    color: '#fbbf24',
    description: 'Cloudflare R2 S3-compatible object storage for video uploads, training content, file attachments.',
    tags: ['cloudflare', 'storage', 's3'],
    meta: { Type: 'S3-compatible', Use: 'Videos · Files' },
  },
  {
    id: 'docker',
    label: 'Docker Compose',
    sublabel: '5 services',
    layer: 'infra',
    position: [-3.5, -8.5, 3],
    size: [2.5, 0.8, 1.8],
    color: '#fde68a',
    description: 'Docker Compose with 5 services: PostgreSQL, Redis, CRM API, Backend API, Frontend.',
    tags: ['docker', 'container', 'devops'],
    meta: { Services: '5', Orchestration: 'Compose' },
  },
  {
    id: 'sentry',
    label: 'Sentry',
    sublabel: 'Error monitoring',
    layer: 'infra',
    position: [1, -8.5, 3],
    size: [2.5, 0.8, 1.8],
    color: '#fde68a',
    description: 'Sentry error tracking and performance monitoring for both frontend (React) and backend (Python).',
    tags: ['monitoring', 'errors', 'performance'],
  },
  {
    id: 'ci-cd',
    label: 'GitHub Actions',
    sublabel: 'CI/CD pipeline',
    layer: 'infra',
    position: [5, -8.5, 3],
    size: [2.5, 0.8, 1.8],
    color: '#fde68a',
    description: 'GitHub Actions CI/CD for automated testing, linting, type checking, and deployment.',
    tags: ['ci', 'cd', 'github-actions'],
  },

  // ===================== EXTERNAL LAYER =====================
  {
    id: 'whatsapp',
    label: 'WhatsApp Cloud API',
    sublabel: 'Meta Business',
    layer: 'external',
    position: [-2, -11.5, 0],
    size: [3, 1, 2],
    color: '#ec4899',
    description: 'WhatsApp Cloud API for automated messaging, notifications, and lead communication.',
    tags: ['whatsapp', 'meta', 'messaging'],
    connections: ['integrations'],
  },
  {
    id: 'n8n',
    label: 'n8n Workflows',
    sublabel: 'Webhook automation',
    layer: 'external',
    position: [2, -11.5, 0],
    size: [3, 1, 2],
    color: '#f472b6',
    description: 'n8n workflow automation platform connected via webhooks for business process automation.',
    tags: ['n8n', 'automation', 'webhooks'],
    connections: ['integrations'],
  },
  {
    id: 'cloudflare',
    label: 'Cloudflare',
    sublabel: 'DNS · CDN · Proxy',
    layer: 'external',
    position: [-5, -11.5, 2.5],
    size: [2.5, 0.8, 1.5],
    color: '#f9a8d4',
    description: 'Cloudflare for DNS management, CDN caching, and DDoS protection.',
    tags: ['cloudflare', 'dns', 'cdn'],
  },
  {
    id: 'render',
    label: 'Render Cloud',
    sublabel: 'Hosting platform',
    layer: 'external',
    position: [5, -11.5, 2.5],
    size: [2.5, 0.8, 1.5],
    color: '#f9a8d4',
    description: 'Render cloud platform for hosting backend, frontend, and microservice deployments.',
    tags: ['render', 'hosting', 'deployment'],
  },
]

export function flattenNodes(nodes: ArchNode[]): ArchNode[] {
  const result: ArchNode[] = []
  for (const node of nodes) {
    result.push(node)
    if (node.children) result.push(...node.children)
  }
  return result
}

export const ALL_NODES = flattenNodes(ARCHITECTURE_NODES)
