"""
Facade for migrating call sites from monolith ``helpers.py``.

Prefer importing from the specific modules (``pipeline_rules``, ``pipeline_legacy``,
``time_ist``, ``row_utils``, ``legacy_status_bridge``) in new code.
"""

from __future__ import annotations

from app.core.legacy_status_bridge import (
    VL2_CONTACTED,
    VL2_LOST,
    VL2_NEW,
    VL2_QUALIFIED,
    VL2_WON,
    legacy_canonical_to_vl2_status,
    vl2_status_labels,
)
from app.core.pipeline_legacy import (
    ADMIN_PIPELINE_BUCKET_CLOSING,
    ADMIN_PIPELINE_BUCKET_ENROLLMENT,
    ADMIN_PIPELINE_BUCKET_TRAINING,
    CALL_RESULT_LEGACY,
    CALL_RESULT_TAGS,
    DAILY_CALL_ENFORCE_START_HOUR_IST,
    DAILY_CALL_TARGET_DEFAULT,
    DAILY_CALL_WARN_CAP,
    FOLLOWUP_TAGS,
    GRACE_MAX_PER_30_DAYS,
    GRACE_REPEAT_THRESHOLD,
    INACTIVITY_BLOCK_CLAIM_HOURS,
    INACTIVITY_LOCK_HOURS,
    INACTIVITY_WARN_HOURS,
    LOW_EFFORT_BLOCK_STREAK,
    LOW_PERF_CALL_THRESHOLD,
    LOW_PERF_STREAK_BLOCK,
    LOW_PERF_STREAK_REMOVE,
    PRE_DAY1_PIPELINE_STAGES,
    QUALITY_MARKET_COLD_MIN_TOUCHED,
    QUALITY_MARKET_COLD_NO_RESPONSE_RATIO,
    QUALITY_TREND_MIN_GOOD_DAYS,
    QUALITY_TREND_WINDOW_DAYS,
    RETARGET_TAGS,
    SOURCES,
    STATUSES,
    TEAM_MY_LEADS_READONLY_STATUSES,
    WORKING_BOARD_HOME_STATUSES,
    WORKING_ENROLLED_STATUSES,
    WORKING_ENROLLMENT_STATUSES,
    WORKING_SIDE_PIPELINE_STATUSES,
    call_result_allowed,
    leader_own_assigned_lead,
    payment_proof_approval_status_value,
    pipeline_stage_for_legacy_status,
    flp_billing_execution_blocked_for_role,
    team_in_pre_day1_execution,
    team_my_leads_status_readonly,
    team_status_dropdown_choices,
    team_status_option_selected,
)
from app.core.pipeline_rules import (
    CALL_STATUS_INTERESTED_BUCKET,
    CALL_STATUS_NO_RESPONSE_BUCKET,
    CALL_STATUS_NOT_INTERESTED_BUCKET,
    CALL_STATUS_VALUES,
    CLAIM_GATE_EXIT_STATUSES,
    PIPELINE_AUTO_EXPIRE_STATUSES,
    SLA_SOFT_WATCH_EXCLUDE,
    STATUS_FLOW_ORDER,
    STATUS_TO_STAGE,
    STAGE_TO_DEFAULT_STATUS,
    TEAM_ALLOWED_STATUSES,
    TEAM_CALL_STATUS_VALUES,
    TEAM_FORBIDDEN_STATUSES,
    TRACKS,
    is_valid_forward_status_transition,
    normalize_flow_status,
    validate_lead_business_rules,
)
from app.core.row_utils import mapping_get as sqlite_row_get
from app.core.time_ist import APP_TIMEZONE_NAME
from app.core.time_ist import SQLITE_NOW_IST
from app.core.time_ist import ist_date_iso
from app.core.time_ist import now_ist as _now_ist
from app.core.time_ist import today_ist as _today_ist

# Legacy names (monolith helpers exposed `_now_ist` / `_today_ist` as private).
now_ist = _now_ist
today_ist = _today_ist

__all__ = [
    "ADMIN_PIPELINE_BUCKET_CLOSING",
    "ADMIN_PIPELINE_BUCKET_ENROLLMENT",
    "ADMIN_PIPELINE_BUCKET_TRAINING",
    "APP_TIMEZONE_NAME",
    "CALL_RESULT_LEGACY",
    "CALL_RESULT_TAGS",
    "CALL_STATUS_INTERESTED_BUCKET",
    "CALL_STATUS_NO_RESPONSE_BUCKET",
    "CALL_STATUS_NOT_INTERESTED_BUCKET",
    "CALL_STATUS_VALUES",
    "CLAIM_GATE_EXIT_STATUSES",
    "DAILY_CALL_ENFORCE_START_HOUR_IST",
    "DAILY_CALL_TARGET_DEFAULT",
    "DAILY_CALL_WARN_CAP",
    "FOLLOWUP_TAGS",
    "GRACE_MAX_PER_30_DAYS",
    "GRACE_REPEAT_THRESHOLD",
    "INACTIVITY_BLOCK_CLAIM_HOURS",
    "INACTIVITY_LOCK_HOURS",
    "INACTIVITY_WARN_HOURS",
    "LOW_EFFORT_BLOCK_STREAK",
    "LOW_PERF_CALL_THRESHOLD",
    "LOW_PERF_STREAK_BLOCK",
    "LOW_PERF_STREAK_REMOVE",
    "PIPELINE_AUTO_EXPIRE_STATUSES",
    "PRE_DAY1_PIPELINE_STAGES",
    "QUALITY_MARKET_COLD_MIN_TOUCHED",
    "QUALITY_MARKET_COLD_NO_RESPONSE_RATIO",
    "QUALITY_TREND_MIN_GOOD_DAYS",
    "QUALITY_TREND_WINDOW_DAYS",
    "RETARGET_TAGS",
    "SLA_SOFT_WATCH_EXCLUDE",
    "SOURCES",
    "SQLITE_NOW_IST",
    "STATUSES",
    "STATUS_FLOW_ORDER",
    "STATUS_TO_STAGE",
    "STAGE_TO_DEFAULT_STATUS",
    "TEAM_ALLOWED_STATUSES",
    "TEAM_CALL_STATUS_VALUES",
    "TEAM_FORBIDDEN_STATUSES",
    "TEAM_MY_LEADS_READONLY_STATUSES",
    "TRACKS",
    "VL2_CONTACTED",
    "VL2_LOST",
    "VL2_NEW",
    "VL2_QUALIFIED",
    "VL2_WON",
    "WORKING_BOARD_HOME_STATUSES",
    "WORKING_ENROLLED_STATUSES",
    "WORKING_ENROLLMENT_STATUSES",
    "WORKING_SIDE_PIPELINE_STATUSES",
    "call_result_allowed",
    "is_valid_forward_status_transition",
    "ist_date_iso",
    "leader_own_assigned_lead",
    "legacy_canonical_to_vl2_status",
    "normalize_flow_status",
    "now_ist",
    "payment_proof_approval_status_value",
    "pipeline_stage_for_legacy_status",
    "flp_billing_execution_blocked_for_role",
    "sqlite_row_get",
    "team_in_pre_day1_execution",
    "team_my_leads_status_readonly",
    "team_status_dropdown_choices",
    "team_status_option_selected",
    "today_ist",
    "validate_lead_business_rules",
    "vl2_status_labels",
]
